new update

diff --git a/bin/update b/bin/update
--- a/bin/update
+++ b/bin/update
@@ -1,261 +1,58 @@
-#!/usr/bin/env bash
-REPOSITORIES=$HOME/Repositories
-STABLE_RUBIES="1.8.6 1.8.7 1.9.1 1.9.2 ree rbx jruby maglev ironruby macruby"
-EDGE_RUBIES="rbx-head ruby-1.8-head jruby-head ruby-head"
-REDMINE=$HOME/redmine
-WORKSPACE=$HOME/Workspace
-FORKS="rails sinatra rack em-redis ebb"
+#!/usr/bin/env bash -e
+export STABLE_RUBIES="1.8.6 1.8.7 1.9.1 1.9.2 ree rbx jruby maglev ironruby macruby"
+export EDGE_RUBIES="rbx-head ruby-1.8-head jruby-head ruby-head ruby-1.9.2-head"
+export RUBIES="$STABLE_RUBIES $EDGE_RUBIES"
+export IMPORTANT_GEMS="bundler backports rspec fuubar minitest gem-open"
 
-. $HOME/.rvm/scripts/rvm
-
-export ARCHFLAGS="-arch x86_64"
-
-function verb() {
-  echo $@ >&2
-  $@
+function cmd() {
+  echo -e "\n\033[0;33m>>>>>>>>>>>> $(date +%H:%m) \033[1;33m$@\033[m" >&2
+  ($@ && echo -e "\n\033[0;32mSUCCESS\033[m") || echo -e "\n\033[0;31mFAIL\033[m"
 }
 
-function announce() {
-  echo -e "\033[0;32m$(date +%H:%m) \033[1;32m$@\033[m" >&2
+function install_missing_gem() {
+  (gem list $@ | grep -q $@ && echo "not missing") || cmd gem install $@
 }
 
-function update_repository() {
-  cd $REPOSITORIES
-  if [ -d $1 ]; then
-    announce "Updating $1"
-    cd $1
-    if [ -d .git ]; then git pull
-    else if [ -d .svn ]; then svn up
-    else if [ -d .hg ]; then hg pull
-    else if [ -d _FOSSIL_ ]; then fossil update
-    else echo "no vcs" >&2; fi; fi; fi
-    fi
-    cd ..
-  fi
-}
-
-function update_cleanup() {
-  update_cleanup_rvm
-  update_cleanup_repositories
-}
-
-function update_cleanup_repositories() {
-  for d in $REPOSITORIES/*/.git; do
-    announce "Cleaning up $d"
-    GIT_DIR=$d git gc --aggressive
-  done
-}
-
-function update_cleanup_rvm() {
-  announce "removing rvm sources"
-  rm -Rf $rvm_path/src
-  unset l186 l187 l191 l192 lmgl ljrb lirb lmrb lrbx lree to_remove
-  for ruby in $(rvm list strings); do
-    case $ruby in
-      ruby-1.8.6-p*)  to_remove="$l186 $to_remove" l186=$ruby;;
-      ruby-1.8.7-p*)  to_remove="$l187 $to_remove" l187=$ruby;;
-      ruby-1.9.1-p*)  to_remove="$l191 $to_remove" l191=$ruby;;
-      ruby-1.9.2-p*)  to_remove="$l192 $to_remove" l192=$ruby;;
-      maglev-*)       to_remove="$lmgl $to_remove" lmgl=$ruby;;
-      jruby-1*)       to_remove="$ljrb $to_remove" ljrb=$ruby;;
-      ironruby-1*)    to_remove="$lirb $to_remove" lirb=$ruby;;
-      macruby-0*)     to_remove="$lmrb $to_remove" lmrb=$ruby;;
-      rbx-1*)         to_remove="$lrbx $to_remove" lrbx=$ruby;;
-      ree-*)          to_remove="$lree $to_remove" lree=$ruby;;
-    esac
-  done
-  for ruby in $to_remove; do
-    announce "removing $ruby"
-    rvm remove $ruby
-  done
-}
-
-function update_repositories() {
-  cd $REPOSITORIES
-  for d in *; do update_repository $d; done
-}
-
-function update_homebrew() {
-  announce "Updating homebrew"
-  brew update
-}
-
-function update_brew() {
-  update_homebrew
-  update_formulas
-}
-
-function update_formulas() {
-  for p in $(brew outdated); do
-    update_formula $p
-  done
-}
-
-function update_formula() {
-  announce "Updating $1"
-  brew install $1
-  case $1 in
-    mysql)      update_brew_launchd $1 com.mysql.mysqld.plist;;
-    postgres)   update_brew_launchd $1 org.postgresql.postgres.plist;;
-    memcached)  update_brew_launchd $1 com.danga.memcached.plist;;
-    mongodb)    update_brew_launchd $1 org.mongodb.mongod.plist;;
-  esac
-}
-
-function update_rvm() {
-  announce "updating rvm"
-  rvm update --head
-  rvm reload
-}
-
-function update_stable_ruby() {
-  rvm use $1 > /dev/null || update_edge_ruby $1
-  rvm use default > /dev/null
-}
-
-function update_edge_ruby() {
-  announce "Updating $1"
-  options=''
-  case $1 in
-    rbx-head) rvm uninstall $1;;
-    ree|1.*) options="-C --with-iconv-dir=$rvm_path/usr -C --cc=clang -C --enable-pthreads";;
-  esac
-  rvm install $1 $options
+function update_redcar() {
+  rvm use ree
+  cd ~/Workspace/redcar
+  git submodule init
+  git submodule update
 }
 
 function update_gems() {
-  announce "Updating gems for $1"
-  rvm use $1 > /dev/null
-  gem update --system
-  gem update --no-verbose
-  gem update --prerelease --no-verbose
-  yes | gem uninstall -a ruby-debug-base
-  gem install ruby-debug
-  rvm use default > /dev/null
-}
-
-function update_all_gems() {
-  for ruby in $STABLE_RUBIES $EDGE_RUBIES; do
-    [ $ruby != ironruby ] && update_gems $ruby
+  for ruby in $RUBIES; do
+    cmd rvm use $ruby
+    #cmd gem update --system
+    cmd gem update
+    for gem in $IMPORTANT_GEMS; do
+      cmd install_missing_gem $gem
+    done
   done
 }
+
+cmd . $HOME/.rvm/scripts/rvm
+cmd export ARCHFLAGS="-arch x86_64"
 
 function update_rubies() {
-  update_rvm
-  for ruby in $STABLE_RUBIES; do update_stable_ruby $ruby; done
-  for ruby in $EDGE_RUBIES;   do update_edge_ruby   $ruby; done
-  update_all_gems
-}
-
-function update_brew_launchd() {
-  target=$HOME/Library/LaunchAgents/$2
-  verb launchctl unload -w $target
-  for plist in /usr/local/Cellar/$1/*/$2; do
-    cp -v $plist $target
+  cmd rvm get head
+  cmd rvm reload
+  for ruby in $STABLE_RUBIES; do
+    cmd rvm use $ruby --install
   done
-  verb launchctl load -w $target
-}
-
-function update_redmine() {
-  announce "Merging redmine commits into finnlabs fork"
-  cd $REDMINE
-  for branch in master 0.9-stable 1.0-stable; do
-    git co $branch && git pull edavis10 $branch && git push origin $branch
-  done
-  git co master && git fetch edavis10 --tags && git push --tags
-}
-
-function update_redmine_dev_tools() {
-  announce "Updating redmine-dev-tools"
-  cd $WORKSPACE/redmine-dev-tools
-  git svn rebase
-  git push
-}
-
-function update_finnlabs() {
-  update_redmine
-  update_redmine_dev_tools
+  for ruby in $EDGE_RUBIES; do
+    rvm use 1.9.2
+    cmd rvm install $ruby
+  done  
+  update_gems
 }
 
 function update() {
-  update_setup
-  update_repositories
-  update_brew
   update_rubies
-  #cleanup_repositories
-}
-
-function update_fork() {
-  announce "Updating github fork of $1"
-  cd $WORKSPACE/$1
-  git remote add $1 git://github.com/$1/$1.git 1>&2 2>/dev/null
-  git co master && git pull origin master && git pull $1 master && git push origin master
-  cd -
-}
-
-function update_forks() {
-  for fork in $FORKS; do
-    update_fork $fork
-  done
-}
-
-function update_all() {
-  update
-  update_forks
-  update_finnlabs
-  cleanup_repositories
-}
-
-function setup_brew() {
-  if [ ! $(which brew) ]; then
-    announce "Installing homebrew"
-    sudo mkdir /usr/local
-    sudo chown -R `whoami` /usr/local
-    curl -L http://github.com/mxcl/homebrew/tarball/master | tar xz --strip 1 -C /usr/local
-    update_formula install git
-    update_formula install pkg-config
-    update_formula install readline
-  fi
-}
-
-function setup_rvm() {
-  if [ ! $(which rvm) ]; then
-    announce "Installing rvm"
-    mkdir -p ~/.rvm/src/ && cd ~/.rvm/src && rm -rf ./rvm/ && git clone --depth 1 git://github.com/wayneeseguin/rvm.git && cd rvm && ./install
-    echo 'if [[ -s $rvm_path/scripts/rvm ]] ; then source $rvm_path/scripts/rvm ; fi' >> ~/.bashrc
-    source ~/.rvm/scripts/rvm
-    rvm package install iconv
-  fi
-}
-
-function setup_structure() {
-  [ $(which libtoolize) ] || ln -s /Developer/usr/bin/glibtoolize /Developer/usr/bin/libtoolize
-  mkdir -p $REPOSITORIES $WORKSPACE
-}
-
-function update_setup() {
-  setup_structure
-  setup_brew
-  setup_rvm
-}
-
-function display_help() {
-  echo "Examples:
-        update                      #   updates everything
-        update setup                #   installes homebrew, rvm, git and such if missing
-        update repositories         #   updates all repositories
-        update repository rails     #   updates rails clone
-        update brew                 #   updates homebrew and all outdated formulas
-        update formulas             #   updates all outdated formulas
-        update formula mysql        #   updates mysql formula + config
-        update rubies               #   updates all rubies + gems"
 }
 
 if [ $1 ]; then
-  case $1 in
-    help|usage|--help|-h|-?) display_help;;
-    *) update_$@;;
-  esac
+  update_$@
 else
   update
 fi
